import { Attachment } from './attachment.model';
import { BaseEntity } from './base-entity';
import { Calendar } from './calendar.model';
import { Comment } from './comment.model';
import { Event } from './event.model';
import { FunctionContext } from './function-context.model';
import { Link } from './link.model';
import { Location } from './location.model';
import { Rating } from './rating.model';
import { StateSpec } from './state-spec.model';
import { Tag } from './tag.model';
import { Vote } from './vote.model';
import { XmEntitySpec } from './xm-entity-spec.model';

export interface XmEntity<D = any> extends BaseEntity {
    type?: XmEntitySpec;
    state?: StateSpec;
    id?: number;
    key?: string;
    typeKey?: string;
    stateKey?: string;
    name?: string;
    startDate?: string | Date;
    updateDate?: string | Date;
    endDate?: string | Date;
    avatarUrl?: string;
    description?: string;
    data?: D;
    removed?: boolean;
    attachments?: Attachment[];
    calendars?: Calendar[];
    locations?: Location[];
    ratings?: Rating[];
    tags?: Tag[];
    comments?: Comment[];
    votes?: Vote[];
    sources?: Link[];
    targets?: Link[];
    functionContexts?: FunctionContext[];
    events?: Event[];
}
