version: '3.3'
services:
    web-app:
        image: xmonline/xm-webapp:${IMAGE_XM_WEBAPP_TAG:-latest}
        networks:
            - xm2
        environment:
            - GATE_HOST=gate-app
        ports:
            - 80:80
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: web-app
                syslog-facility: local7

networks:
    xm2:
        driver: overlay

