---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: consul-service
spec:
  ports:
    - name: consul-port
      port: 8500
      targetPort: 8500
  selector:
    app: consul
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
spec:
  progressDeadlineSeconds: 1600
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - env:
            - name: PORT
              value: "8500"
          image: consul:1.14.4
          name: consul-container
          ports:
            - containerPort: 8500
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 8500
