---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gate
  name: gate-service
spec:
  ports:
    - name: gate-port
      port: 8080
      targetPort: 8080
  selector:
    app: gate
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-deployment
spec:
  progressDeadlineSeconds: 1600
  replicas: 1
  selector:
    matchLabels:
      app: gate
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
        - env:
            - name: _JAVA_OPTIONS
              value: "-Xmx256m -Xms256m"
            - name: PORT
              value: "8080"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul-service"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          image: xmonline/xm-gate:latest
          name: gate-container
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 150
            tcpSocket:
              port: 8080
      initContainers:
        - command:
            - 'sh'
            - '-c'
            - 'until nc -vz config-service 8084 ; do echo "config-service"; sleep 1; done;'
          image: busybox:latest
          name: init-config-service
