---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
spec:
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  progressDeadlineSeconds: 1600
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://kafka-service:9092,OUTSIDE://localhost:29092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INSIDE"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
          image: confluentinc/cp-kafka:6.1.9
          name: kafka-container
          ports:
            - containerPort: 9092
            - containerPort: 29092
          readinessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: 9092
      initContainers:
        - command: [ 'sh', '-c', 'until nc -vz zookeeper-service 2181; do echo "zookeeper-service"; sleep 1; done;' ]
          image: busybox:latest
          name: init-zookeeper-service
