---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-service
spec:
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  progressDeadlineSeconds: 1600
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_MULTIPLE_DATABASES
              value: 'uaa,entity,dashboard'
          image: debezium/postgres:14
          name: postgres-container
          ports:
            - containerPort: 5432
          readinessProbe:
            initialDelaySeconds: 2
            tcpSocket:
              port: 5432
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-initdb
      volumes:
        - configMap:
            name: postgres-initdb-config
          name: postgres-initdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    SELECT 'CREATE USER uaa WITH PASSWORD ''password'' CREATEDB'
    WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'uaa')\gexec
    
    SELECT 'CREATE USER entity WITH PASSWORD ''password'' CREATEDB'
    WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'entity')\gexec
    
    SELECT 'CREATE USER dashboard WITH PASSWORD ''password'' CREATEDB'
    WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'dashboard')\gexec
    
    SELECT 'CREATE DATABASE uaa WITH OWNER = uaa ENCODING = ''UTF8'' LC_COLLATE = ''en_US.utf8'' LC_CTYPE = ''en_US.utf8'' TABLESPACE = pg_default CONNECTION LIMIT = 10'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'uaa')\gexec
    
    SELECT 'CREATE DATABASE entity WITH OWNER = entity ENCODING = ''UTF8'' LC_COLLATE = ''en_US.utf8'' LC_CTYPE = ''en_US.utf8'' TABLESPACE = pg_default CONNECTION LIMIT = 10'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'entity')\gexec
    
    SELECT 'CREATE DATABASE dashboard WITH OWNER = dashboard ENCODING = ''UTF8'' LC_COLLATE = ''en_US.utf8'' LC_CTYPE = ''en_US.utf8'' TABLESPACE = pg_default CONNECTION LIMIT = 10'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dashboard')\gexec
