---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp-service
spec:
  ports:
    - name: webapp-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  progressDeadlineSeconds: 1600
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - env:
            - name: GATE_HOST
              value: "gate-service.default.svc.cluster.local"
            - name: GATE_PORT
              value: "8080"
            - name: PORT
              value: "80"
          image: xmonline/xm-webapp:latest
          name: webapp-container
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
