version: '3.3'
services:
    activation-app:
        image: xmonline/tmf-ms-activation:${IMAGE_TMF_MS_ACTIVATION_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/activation-app.env
        secrets:
            - source: ACTIVATION_SPRING_DATASOURCE_PASSWORD
              target: SPRING_DATASOURCE_PASSWORD
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: activation
                syslog-facility: local7
secrets:
    ACTIVATION_SPRING_DATASOURCE_PASSWORD:
        external: true
networks:
    xm2:
        driver: overlay
