version: '3.3'
services:
    scheduler-app:
        image: xmonline/xm-ms-scheduler:${IMAGE_XM_MS_SCHEDULER_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/scheduler-app.env
        secrets:
            - source: SCHEDULER_SPRING_DATASOURCE_PASSWORD
              target: SPRING_DATASOURCE_PASSWORD
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        logging:
            driver: syslog
            options:
                tag: scheduler
                syslog-facility: local7

secrets:
    SCHEDULER_SPRING_DATASOURCE_PASSWORD:
        external: true

networks:
    xm2:
        driver: overlay
